version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: blueflix
    restart: always
    volumes:
      - postgres-disk:/var/lib/postgresql/database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: blueflix
volumes:
  postgres-disk:
